### ISSUE TITLE
Add an option to deploy the app to AWS App Runner

### ISSUE THREAD

**Issue by jackishere** [IsraelAzoulay/MeteoMate#14]
Add an option to deploy the app to aws app runner
- [ ] create the infra with AWS console
- [ ] Create the infra with AWS CLI
- [ ] Every commit the GH actions will test and push a docker container to AWS ECR - build and push workflow
- [ ] Every new tag the GH actios will deploy the latest container to AWS App runner
- [ ] Identify and verify edge cases

**Comment by IsraelAzoulay** [comment]
Updated the deployment process.
